"""empty message

Revision ID: 11feefc7b905
Revises: 6d6ab6571d71
Create Date: 2020-04-23 10:35:19.694245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11feefc7b905'
down_revision = '6d6ab6571d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warning_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('occur_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warning_info')
    # ### end Alembic commands ###
