"""empty message

Revision ID: 1379d698fb03
Revises: 67de18113104
Create Date: 2020-04-19 15:08:14.783045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1379d698fb03'
down_revision = '67de18113104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_heat_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_heat_map')
    # ### end Alembic commands ###
