"""empty message

Revision ID: 23b5a951c8ed
Revises: 13778264b70e
Create Date: 2020-04-17 17:38:43.966791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b5a951c8ed'
down_revision = '13778264b70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time')
    # ### end Alembic commands ###
